# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_error_pred_seg_VAR1 <- function(X_futu, X_curr, s, e, lambda, delta, eps) {
    .Call(`_amoc_rcpp_error_pred_seg_VAR1`, X_futu, X_curr, s, e, lambda, delta, eps)
}

rcpp_DP_VAR1 <- function(X_futu, X_curr, gamma, lambda, delta, eps) {
    .Call(`_amoc_rcpp_DP_VAR1`, X_futu, X_curr, gamma, lambda, delta, eps)
}

amoc_dp_var1 <- function(X_futu, X_curr, lambda, delta, eps) {
    .Call(`_amoc_amoc_dp_var1`, X_futu, X_curr, lambda, delta, eps)
}

rcpp_soft_threshold_scalar <- function(x, lambda) {
    .Call(`_amoc_rcpp_soft_threshold_scalar`, x, lambda)
}

rcpp_lasso_standardized_obj <- function(Xtilde, Ytilde, beta, lambda) {
    .Call(`_amoc_rcpp_lasso_standardized_obj`, Xtilde, Ytilde, beta, lambda)
}

rcpp_lasso_standardized <- function(Xtilde, Ytilde, beta_start, lambda, eps) {
    .Call(`_amoc_rcpp_lasso_standardized`, Xtilde, Ytilde, beta_start, lambda, eps)
}

rcpp_lasso_standardized_seq <- function(Xtilde, Ytilde, lambda_seq, eps) {
    .Call(`_amoc_rcpp_lasso_standardized_seq`, Xtilde, Ytilde, lambda_seq, eps)
}

rcpp_standardizeXY <- function(X, Y) {
    .Call(`_amoc_rcpp_standardizeXY`, X, Y)
}

rcpp_lasso_seq <- function(X, Y, lambda_seq, eps) {
    .Call(`_amoc_rcpp_lasso_seq`, X, Y, lambda_seq, eps)
}

rcpparma_hello_world <- function() {
    .Call(`_amoc_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_amoc_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_amoc_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_amoc_rcpparma_bothproducts`, x)
}

